### ISSUE TITLE
Tunnel stops on server restart

### ISSUE THREAD

**Issue by Schuischta** [WisdomSky/Cloudflared-web#38]
Hi, every time my server restarts, the tunnel stops working. I then have to go to the web UI and click 'Stop' and then 'Start' again for the tunnel to work.

**Comment by Zoobdude** [comment]
Could you attach some logs after the restart?

**Comment by Schuischta** [comment]
It seems to work as for now. If it happens again i will attach the logs.

**Comment by Schuischta** [comment]
[_cloudflared_web_logs.txt](https://github.com/user-attachments/files/17304171/_cloudflared_web_logs.txt)
It happend again. Here are the logs.

**Comment by WisdomSky** [comment]
@Schuischta 

have you tried setting custom DNS server when running the container?

https://docs.docker.com/engine/network/#dns-services

If you are using docker compose you can di it as such:


```yaml
services:
  cloudflared:
    image: wisdomsky/cloudflared-web
    dns:
      - 1.1.1.1
      - 8.8.8.8
```
