### ISSUE TITLE
Container crashes on latest / 11.1 branche

### ISSUE THREAD

**Issue by Toomblr** [WisdomSky/Cloudflared-web#48]
I ran an update on my container which uses your image with `:latest` branch.
As soon as I started the container it got stuck in a restartloop. I tried deleting the contents of the /config folder. This worked, however, when I entered the cloudflare token in the webgui the container went into restartloop again.

Workaround:
Switching to `:2024.11.0` branch.

This is my compose:
```
services:
  cloudflared-web:
    image: wisdomsky/cloudflared-web:2024.11.0
    environment:
      - TZ=${TZ}
      - WEBUI_PORT=14333
    volumes:
      - /mnt/ssd0/docker/data/cloudflared/config:/config
    networks:
      - npm
    restart: unless-stopped
networks:
  npm:
    external: true
```
