### ISSUE TITLE
a better way to implement healthcheck?

### ISSUE THREAD

**Issue by captmicr0** [WisdomSky/Cloudflared-web#8]
Currently adding healthchecks to all my docker containers, and this container specifically was quite hard to implement one for.

I wanted the healthcheck to be based on the status of the tunnel connection, giving a healthy status when the tunnel is connected.

Right now I'm using this in my docker-compose file:
```
healthcheck:
      test: "[[ $(curl -s -L http://localhost:14333/config | node -e 'console.log(JSON.parse(require(\"fs\").readFileSync(0).toString()).start)') == true ]]"
      interval: 30s
      timeout: 10s
      retries: 5
```

Any plans to implement a healthcheck in the Dockerfile itself?
