### ISSUE TITLE
Support for extra CLI commands - specifically metrics 

### ISSUE THREAD

**Issue by MariusVB** [WisdomSky/Cloudflared-web#9]
Hi,

I would like to also have the metrics server running. Do you have support for extra CLI commands, specifically metrics?
https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/monitor-tunnels/metrics/

**Comment by WisdomSky** [comment]
Hi @MariusVB,

Right now, other cloudflared cli flags aren't supported.
Will take note of this and consider implementing it.

**Comment by MariusVB** [comment]
Hero!

**Comment by WisdomSky** [comment]
Hi @MariusVB,

Using Tunnel Metrics is now supported starting on `2024.2.1`. (re-pull the image if you are currently using the same tag)

```yaml
services:
  cloudflared:
    image: wisdomsky/cloudflared-web:latest
    restart: unless-stopped
    network_mode: host
    environment:
      METRICS_ENABLE: 'true'
 ```
 
 The default port of the metrics server is `60123`, however you can change it to something else by specifying the `METRICS_PORT` environment variable.
